apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::741414918659:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::741414918659:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AD6VTJTIKAUW
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-07T06:10:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1346"
  uid: 1cca41b5-7fac-46f5-89cb-1d543666156e
